### ISSUE TITLE
Export Tool - New Map Folders

### ISSUE THREAD

**Issue by macsims1** [mapaction/mapaction-toolbox#113]
On export create a new folder for contents of export to go to. Currently before exprting you need to manually create a folder before exporting, otherwise it all goes into 3_Mapping\34_Map_Products_MapAction. Folder name could be based on the MA number in top right - MA001, MA002, etc. If there is a new version then MA002_v2, MA002_v3, etc. If it already exists but you just want to overwrite - SB have come back with some QA points, then "this folder already exists, do you want to overwrite? option  is given.

**Comment by clairebyrne** [comment]
@macsims1 Implemented in toolbar Version: 4.1.7413.28049, dated 18/04/2020 (and possibly before!).
The base toolbar export path is 34_Map_Products_MapAction by default. On export a new folder is created there based on the map_no, which now includes the version number. 
If the folder exists already, it is overwritten **without** warning. 
We might need to review that behaviour but closing this one for now.
