### ISSUE TITLE
.esriAddIns not in GitHub repository

### ISSUE THREAD

**Issue by chrisewing** [mapaction/mapaction-toolbox#114]
Please could we put the .esriAddIns in the the repository in a release folder or something similar?

The last release was 12 Sep 2013!

**Comment by andrewphilipsmith** [comment]
Done for now:
https://github.com/mapaction/mapaction-toolbox/releases/tag/3.1.5415.30845

Through we need to make it standard practice to add updated addins to Github releases, when we update the laptops.
