### ISSUE TITLE
Layer Rename Tool: Issues (will be split out into separate ones!)

### ISSUE THREAD

**Issue by chrisewing** [mapaction/mapaction-toolbox#115]
- permissions drop down
- make copy of data and put into active folder (don't rename the only copy of dataset)
- shapefile type should be pre-populated
- put csv files into crash move folder
- put help file on wiki
- updates to data naming convention be reflected into the csv files
- need installation / config script (make sure it's ready for use by deployable team)

**Comment by andrewphilipsmith** [comment]
@pjrobinuk I think that most of these comments are ones you have already put in pivotal tracker. Please could you double check that there is nothing here you're not already aware of and either add to them to PT or add them as bugs here? Then we could close this issue. Many thanks.
