### ISSUE TITLE
Export tool - Validation not working for Themes tab

### ISSUE THREAD

**Issue by andrewphilipsmith** [mapaction/mapaction-toolbox#130]
# How to recreate:

MET v4.0.6013.24320
ArcGIS v10.2.2
Windows 7 64bit
- Setup an appropriate operational_config.mxl.
- Open a suitable map.
- Open the Export Tool dialogue and switch to the Themes tab.
# Expected behaviour:
- There should be a minor warning if no themes are selected. The message should have appropriate wording.
- There should be a warning if the country field is empty or does not match the value set in the operational_config.xml. The message should have appropriate wording.
# Actual behaviour:
- On form load, when no themes are selected there is a validation  message "Textbox is empty".This text doesn't make sense for a checkbox list.
- If some themes are selected and deselected, so that there a again no themes selected, there is no validation error.
- The validation error for the country field is displayed at all times irrespective of the actual stae of this text box. (message "Textbox is empty)

**Comment by shurst-ma** [comment]
Hi Andy,
I'm afraid I've done it again.

I've added
https://raw.githubusercontent.com/mapaction/mapaction-toolbox/master/arcgis10_mapping_tools/MapActionToolbars/FormValidationExport.cs
https://raw.githubusercontent.com/mapaction/mapaction-toolbox/master/arcgis10_mapping_tools/MapActionToolbars/frmExportMain.cs

to the Main branch.

I have to wrap it up now, but I need to back these out of the main branch
and get them onto  the "taborder" branch.
https://github.com/mapaction/mapaction-toolbox/tree/bugfix/taborder/arcgis10_mapping_tools/MapActionToolbars

I won't be able to do this until tomorrow night at the earliest.
Sorry to muck you about.

-Steve

**Comment by clairebyrne** [comment]
@andrewphilipsmith @shurst-ma  
FYI these issues remain when tested on these specs:
Toolbar Version: 4.1.7413.28049
ArcGIS Version and Edition: 10.6.1 Advanced single use
MapAction laptop (yes/no): no
Windows Version: 10 Home 10.0.18362

**Comment by harry-gibson** [comment]
Also fixed the double-click-needed issue for donors checkboxes, in commit d60b93b
