### ISSUE TITLE
Confirm that Exported PDF's are Geo-referenced

### ISSUE THREAD

**Issue by kes1** [mapaction/mapaction-toolbox#136]
USA-2 USAR team use [Avenza ](http://www.avenza.com/pdf-maps)to view geo-referenced PDF's and GeoTiff's on their mobile devices.  

Can/does the export tool export maps with geo-referencing enabled, and could this be supported?  

From initial trials with the team maps need to be in WGS1984 when exported to work with Avanza, but it may support other projections.

**Comment by KarlHennermann** [comment]
The MapAction export tool by default produces GeoPDF.
To try with Adobe Reader DC: Open a map PDF > Tools > Measure. 
You can also do basic mark-up in Adobe Reader DC (right-click).

For advanced mark-up and (kind of) sync data back to a GIS you need Avenza's maps app, www.avenzamaps.com

See also: http://www.mapaction.org/wiki/index.php?title=PDF_Maps_and_GeoPDFs

**Comment by kes1** [comment]
Thanks Karl - I hadn't known about the measure tool in Acrobat Reader either.  

Using that test the export tool does seem to be including the georeference information.  This was implemented at 9.3, and can now be [set explicitly](http://desktop.arcgis.com/en/arcobjects/latest/net/webframe.htm#IExportPDF2.htm) before the PDF export.

**Comment by clairebyrne** [comment]
Confirmed. Closing issue.
