### ISSUE TITLE
layout tool should update time_zone element

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#180]
## Expected Behavior
Layout tool should update **time_zone** element on map canvas. 
Element checker should check for the presence of the **time_zone text element** 

## Actual Behavior
Layout tool updates **timezone** element on map
Element checker checks for presence of timezone text element

## Steps to Reproduce the Problem

  1. Open layout tool
  2. Change time zone 
  3. Observe which element has been updated on map canvas
  4. Click element checker (cog in top right of layout tool). Observe timezone element listed

## Specifications

  
  - Toolbar Version: 4.1.7459.3891
  - ArcGIS Version and Edition: 10.6.1
  - MapAction laptop (yes/no): no
  - Windows Version: 10

**Comment by harry-gibson** [comment]
Currently the original **timezone** element still exists on the map canvas (as well as **time_zone**). This fix changes the tool to update both elements (if they are both present).
