### ISSUE TITLE
Remove Scale from layout tool

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#181]
## Expected Behavior
The text element named **scale** has been replaced with a dynamic Scale text element in the templates. 
There is no longer any requirement to have the Layout tool update this element. 
There is also no longer a requirement to check for this element in the element checker. 
The Export tool takes the Scale value directly from the main data frame. 

## Actual Behavior
Tool expects a simple text element named **scale** and compares its value to the scale of the main data frame. Tool currently does not find this element as it no longer exists. 

## Specifications

  - Toolbar Version: 4.1.7459.3891
  - ArcGIS Version and Edition: 10.6.1
  - MapAction laptop (yes/no): no
  - Windows Version: 10

**Comment by harry-gibson** [comment]
Fixed on branch remove-layout-scale, now merged into bugfix

Fix incorporated edit to MapActionToolbarsConfig.xml which was corrupted, which in the existing code prevented the config/export tools from loading. Also swallow error from QR generation so it does not prevent layout update. (QR generation itself still needs fixing).
