### ISSUE TITLE
set Access value to default to "Public" 

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#183]
## Expected Behavior  
The Access field in the Export Tool should default to "Public". 

## Actual Behavior
The Access field in the Export Tool should default to empty. 

## Steps to Reproduce the Problem

  1. Launch the Export tool
  2. Go to Map Catalogue tab
 
## Specifications

- Toolbar Version: 4.1.7459.3891
- ArcGIS Version and Edition: 10.6.1
- MapAction laptop (yes/no): no
- Windows Version: 10

**Comment by harry-gibson** [comment]
Are we sure this is a good idea? seems like it's a bit risky to default to public if the user omits to remember to set it to "selected partners" when it should have been?

The code which parses the value from the previous export has been fixed so if the same map and version are exported multiple times then the access field will be populated as it was last time round. (But if the version is augmented then currently it will go back to blank).

Please comment to advise if we should proceed with always defaulting to public or if this fix will do?

**Comment by harry-gibson** [comment]
Have implemented this, but also re-instated code to read value from previous export, thus if a map has already been exported with a different access setting then this will be used, otherwise Public will be default
