### ISSUE TITLE
Make Disclaimer and Donor credits boxes a few lines deeper in layout tool

### ISSUE THREAD

**Issue by clairebyrne** [mapaction/mapaction-toolbox#184]
## Expected Behavior
Fully utilise the UI space available on the Standard tab in the Layout Tool. 

## Actual Behavior
The boxes for Donor and Disclaimer are barely big enough to show the default values for these without having to scroll. 
There's plenty of room to increase the depth of the boxes on the UI.

## Specifications

- Toolbar Version: 4.1.7459.3891
- ArcGIS Version and Edition: 10.6.1
- MapAction laptop (yes/no): no
- Windows Version: 10

**Comment by harry-gibson** [comment]
increased size enough to fit default text plus 2 more lines. 
Please re-open issue if this is still insufficient as the current dialog could hold a bit more if needed.
