### ISSUE TITLE
Excessive export files sizes due to jpeg quality settings

### ISSUE THREAD

**Issue by stringfellow** [mapaction/mapaction-toolbox#76]
_From [andrewphilipsmith](https://code.google.com/u/andrewphilipsmith/) on October 28, 2013 19:15:38_

What steps will reproduce the problem? 1. Export a map What is the expected output? Manually exporting a map and choosing 75&#37; quality setting for jpegs produces files of 1-2Mb size. What do you see instead? Using the export tool the jpeg and pdf file sizes are very large (5-7Mb) and the quality setting is 100&#37;. If not what version of the product are you using? On what operating system and what version of ArcMap? ArcMap 10.1, W7 Please provide any additional information below.

_Original issue: http://code.google.com/p/mapaction-toolbox/issues/detail?id=76_

**Comment by andrewphilipsmith** [comment]
Believed fixed at v4.0.6013.24320
See #129  and fe35735c8a007ebc716b8e52147e0b0f22b065f5
