### ISSUE TITLE
Export tool does not create zip file

### ISSUE THREAD

**Issue by stringfellow** [mapaction/mapaction-toolbox#86]
_From [matt.si...@googlemail.com](https://code.google.com/u/114649005702588861338/) on February 24, 2014 12:20:50_

Reported by Karl following South Sudan deployment

Export tool does not create zip file (issue observed on LT57 with MA014 to MA027). No error message. Apart from this the export tool works great, love it!

_Original issue: http://code.google.com/p/mapaction-toolbox/issues/detail?id=86_

**Comment by andrewphilipsmith** [comment]
Believed fixed at v4.0.6013.24320
See #129  and fe35735c8a007ebc716b8e52147e0b0f22b065f5
